### ISSUE TITLE
Missing bracket in nanodac_loop_pid.template

### ISSUE THREAD

**Issue by ccw63** [ISISComputingGroup/EPICS-nanodac#1]
https://github.com/ISISComputingGroup/EPICS-nanodac/blob/e8017286ae2b1683bca4b5eab2698fbc4589acac/eurothermApp/Db/nanodac_loop_pid.template#L793

I believe there is a missing bracket at the location linked above.

I got ```dbReadCOM: Parser stack dirty w/o error. 1``` when the IOC reached the expanded nanodac.db file. Adding the bracket fixed the error.

**Comment by FreddieAkeroyd** [comment]
@ccw63 Thank you - now corrected. If you were looking for a more recent version of this module see https://github.com/ornl-epics/eurotherm

**Comment by ccw63** [comment]
@FreddieAkeroyd Thanks! I will take a look at the linked version.
